### ISSUE TITLE
color space not suported 

### ISSUE THREAD

**Issue by allan1096** [EndlesslyFlowering/ReShade_HDR_shaders#1]
hi, for some reason i wanted to see if i can analyze the HDR in hitman 3 but the reshade preset show me a big "color space not supported" i dont know what is wrong because my display has the 10bit signal, RGB Full and HDR active but still i cant figure it out

**Comment by EndlesslyFlowering** [comment]
I really need to write a guide...

**Comment by allan1096** [comment]
oh ok thank you for your answer

**Comment by EndlesslyFlowering** [comment]
> oh ok thank you for your answer

let me know if it works :)

**Comment by allan1096** [comment]
> > oh ok thank you for your answer
> 
> let me know if it works :)

HI, thanfully it worked like a charm and also let me analyze even auto HDR games :D

**Comment by EndlesslyFlowering** [comment]
> > > oh ok thank you for your answer
> > 
> > 
> > let me know if it works :)
> 
> HI, thanfully it worked like a charm and also let me analyze even auto HDR games :D

Glad to hear that it worked out :)
