### ISSUE TITLE
Hdr analysis tool not properly reading/displaying data

### ISSUE THREAD

**Issue by troco72** [EndlesslyFlowering/ReShade_HDR_shaders#11]
The min and max cll isn't effected whatsoever nor are the colors effected whenever I adjust the black level. 

And turning on and off the black floor doesn't touch the graph that we use to see the black floor and look out for crush and raise. 

Reshade and the shaders are at the newest versions.

Any idea? :/

The changes I do to the black floor doesn't change any of the numbers or colors on the analysis tool.

No adjustment can be made using your black floor shader, that will effect the readings of your analysis tool. 

Lies of P steam version. 

Win 11 4090 13900k 64gigs ram plenty of storage space newest gpu drivers. 

Tried native resolution and not using dlaa. (Was using dldsr + dlaa) 

Tried restarting my pc. 

Your analysis tool + the prod80 curved levels shader I've always used successfully in the past. And are still working together In unison for cyberpunk for example. 

If there's any information I could provide just let me know :)

**Comment by EndlesslyFlowering** [comment]
the HDR analysis shader needs to be below all other shaders in your shader order
like here:
![image](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/assets/19245343/8fc66b53-f969-46cb-8f29-d93cfb349440)

**Comment by troco72** [comment]
You're the best! Thanks so much! This tool has effectively turned hdr on pc into something worthwhile and it's been amazing for the community.  Thanks for the work you do , and I appreciate the quick help! 

By chance would you have a good way of describing the difference / different use cases for sdr black floor emulation vs enable black floor lowering. 

After playing around with them a bunch and seeing what they do. It appears that the black floor emulation effects mid tones more.  

They both effect color but in different ways. 

So it seems you'd want to use black floor lowering when you only want to effect the blacks. 

While you'd want to use the sdr emulation for a washed out picture with blown out mids? 

Do you have some personal general idea for using these? :) 

Also if what I said is correct. Is there a way to test for blown out mids with your tools , or is the ol eye test the method?

**Comment by EndlesslyFlowering** [comment]
- SDR Black Floor emulation is for when you think the black floor in HDR does not match the black floor in SDR
  - to test this:
    - set the Windows desktop to SDR and open the game in SDR
    - evaluate the black floor (don't take screenshots as this causes a mismatch because Windows behaves weirdly)
    - close the game
    - set the Windows desktop to HDR and open the game in HDR
    - if the black floor looks raised or the game looks more "washed out" compared to SDR, this is the option to use

- Black Floor lowering is for when the black floor doesn't hit true black no matter what

both can be used in combination to achieve a desired effect

> It appears that the black floor emulation effects mid tones more.
that is true. at around 12.54% of the nits you choose it will start making things a little bit more bright

> Also if what I said is correct. Is there a way to test for blown out mids with your tools , or is the ol eye test the method?
yeah just eye-ball it

**Comment by troco72** [comment]
I feel bad commenting again but there's only one thing left I need to clarify and then I think I'll have It.

So I'll name an example this a bit odd as a standard one I feel would be simpler.  

In the game lies of p. There's a very slight black level raise.  The min cll is I believe it was 0.00087. 

Using the sdr black floor emulation even at its lowest nits seems to be overkill. And perhaps introduce crush? Not sure. 

My goal is to make the white line on the graph slowly go down until its just barely not visible anymore right? And that would introduce perfect blacks with minimal crush is my thought process. 

To do a more subtle adjustment I'd have to use the other one. 

And I can achieve the desired effect of just barely lowering the black floor until the white line is noonger visible,  however even that I Can do it two ways , with a bigger focus on the black point roll off,  or with a bigger focus and the new black point. 

What's your thoughts on this example of a situation? Honestly the sdr black floor emulation on its lowest nits and even up to 65 looks good. I feel like the mids look blown out. But it wouldn't make much sense considering the very minimal black floor raise.

**Comment by EndlesslyFlowering** [comment]
> Using the sdr black floor emulation even at its lowest nits seems to be overkill. And perhaps introduce crush? Not sure.

The SDR black floor emulation can crush detail because the data has to go somewhere (especially in HDR10). IMHO this is negligible. If the black floor already followed how SDR looks you probably couldn't tell the difference.

> Honestly the sdr black floor emulation on its lowest nits and even up to 65 looks good.

if you `CTRL` + `LEFT CLICK` on the slider you can type an any value you want (even lower/higher than the limit of the slider). try it out :) I don't prevent this stuff.

> I feel like the mids look blown out.

I'll look into to adding an option to just adjusting the blacks and not raising the mids.
Though this is an intended effect (raising the mids a little) because of how the mismatch happens in the first place.

**Comment by troco72** [comment]
Oh this is incredibly useful thanks for explaining that I could do that! 

I actually ended up going the route of typing the highest number possible of sdr emulation until crushing occurs. And then used the other option to bring the black floor down until it was perfect blacks. Figured I'd get the best of both worlds

However I do still wonder if there's a general idea of which blackpoint roll off to use. 

Huh funny enough I actually meant I thought the game looks a little blown out natively not when using your tools. If anything ive always liked that it doesnt only touch blacks, as you get a huge boost in hdr colors that way. That's awesome you're going to add that option though! 

However I would've expected simply setting the blackpoint roll off to 1 nit or some number close to that would be the way to only effect the blacks. I suppose not 🤷‍♂️ it's all a bit confusing at times but thanks for helping me get the reign on things. 

Have a good one :)

**Comment by EndlesslyFlowering** [comment]
> However I would've expected simply setting the blackpoint roll off to 1 nit or some number close to that would be the way to only effect the blacks.

I actually don't recommend this because as mentioned before "the data has to somewhere" so having a long enough roll off is important.

I also just discovered an issue in this shader and fixed it.
You can download the latest master here: https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/archive/refs/heads/master.zip

**Comment by EndlesslyFlowering** [comment]
> I feel like the mids look blown out.

finally added in latest release :)
[Release 2024.03.04](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/releases/tag/2024.03.04)
