### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by totorb2x** [EndlesslyFlowering/ReShade_HDR_shaders#12]
Hello,

i try to make lilium work on Dark Souls 3 (steam), with Majorpainthecactus.

"Major pain" works (with error 193)  and lillium features showing an error too and doesn't work :  "Only hdr color space are supported."

My screen : vg279qm  .
Hdr : on.
Autohdr : off

**Comment by EndlesslyFlowering** [comment]
"error 193" seems to be the wrong AutoHDR.addon file being loaded.
as long as the tab for the plugin shows up this can be ignored :)

**Comment by totorb2x** [comment]
"you need to overwrite the colour space for the the MajorPainTheCactus add-on since the changes don't get correctly forwarded to my shaders"    That's work !!!

Thank you for your help and tips ;)
