### ISSUE TITLE
reshade menu making HDR work on broken deck OLED games?!           

### ISSUE THREAD

**Issue by tehoblivious** [EndlesslyFlowering/ReShade_HDR_shaders#13]
I am so confused how this actually fixed broken HDR games when the reshade menu was open 
(( BUT isn't a proper solution because you can't play anything with the reshade menu open )) 

https://www.youtube.com/watch?v=fY0L3IDc-v8

you guys are basically HDR developers, I already put it on the reshade forum 
but maybe you guys know some things too 
i'm lost 
like how does just having the reshade menu open "FIX" broken HDR games on deck 
(see what i mean in my video above)

**Comment by EndlesslyFlowering** [comment]
Opening the ReShade menu creates a back buffer render target view iirc and then copies to the back buffer again I think. Not sure how it all works.
The games you posted all seem to be scRGB and the issue you are seeing is that every colour above 1.0 which translates to 80 nits gets cut off.
Am I understanding it right, that when you just open the game without ReShade loaded for the game it's working incorrectly?
Also what release channel are you on? stable/beta/preview?
And have you changed any specific display settings or others that could affect this?

**Comment by EndlesslyFlowering** [comment]
Also if you are using any mods or tweaks for the deck, like decky stuff. Disable all of it or uninstall them all if still doesn't work. Then test again. Those are highly likely the issue.
Control HDR patch works fine here.
