### ISSUE TITLE
Has knee factor been renamed/removed? Tone Mapping 

### ISSUE THREAD

**Issue by ZebedeeZ** [EndlesslyFlowering/ReShade_HDR_shaders#14]
Hello. I watch Plasma TV for Gaming on Youtube and in a video from about 5 months ago he uses the 'knee factor' setting in the Tone Mapping shader to increase brightness. I can't find that setting in the latest version of your shaders. Has it been renamed or replaced with something else? If so, how would you now increase brightness? Thank you.

**Comment by EndlesslyFlowering** [comment]
I had to remove the % value as it causes issues.

There is a new knee offset setting which replaces it and does not cause issues.
