### ISSUE TITLE
Failed to compile lilium__hdr_analysis.fx

### ISSUE THREAD

**Issue by Areteic** [EndlesslyFlowering/ReShade_HDR_shaders#17]
Hello!
Sorry to bother you but I cannot get hdr_analysis from any of 2024 releases to work for me in Elden Ring.
I am using ReShade 6.0.1.1823, Nvidia driver version is 551.61.

After installing any of 2024 releases with removing all of the old files beforehand, ReShade was reporting following error:
```
07:55:59:241 [18964] | ERROR | Failed to compile "C:\Software\ReShade\reshade-shaders\Shaders\lilium__hdr_analysis.fx":
C:\Software\ReShade\reshade-shaders\Shaders\lilium__include/hdr_analysis.fxh(1488, 4): error X3004: undeclared identifier 'encodedPixel'
C:\Software\ReShade\reshade-shaders\Shaders\lilium__hdr_analysis.fx(1052, 13): error X3004: undeclared identifier 'CSP_DESC_TEXT_LENGTH'
```
But if I add to ReshadePreset.ini file an override line `PreprocessorDefinitions=CSP_OVERRIDE=CSP_HDR10` (since I always had to enforce HDR10 for shader to work with Elden Ring on old releases) then I get different error code:
```
07:56:04:766 [02376] | ERROR | Failed to compile "C:\Software\ReShade\reshade-shaders\Shaders\lilium__hdr_analysis.fx":
C:\Games\Steam\steamapps\common\ELDEN RING\Game\Shader@0x0000020EBDA18520(3134,15-35): error X3504: array index out of bounds
```
[ReShade.log](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/files/14391348/ReShade.log)

Thanks!

**Comment by EndlesslyFlowering** [comment]
fixed with 65c606618d3283d7033cf5f238cc0d25a14462fb

**Comment by EndlesslyFlowering** [comment]
> But if I add to ReshadePreset.ini file an override line `PreprocessorDefinitions=CSP_OVERRIDE=CSP_HDR10` (since I always had to enforce HDR10 for shader to work with Elden Ring on old releases) then I get different error code:
> 
> ```
> 07:56:04:766 [02376] | ERROR | Failed to compile "C:\Software\ReShade\reshade-shaders\Shaders\lilium__hdr_analysis.fx":
> C:\Games\Steam\steamapps\common\ELDEN RING\Game\Shader@0x0000020EBDA18520(3134,15-35): error X3504: array index out of bounds
> ```
> 
> [ReShade.log](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/files/14391348/ReShade.log)
> 
> Thanks!

should be fixed with b5eb8025a80944eb493f3035dbe14a546f0dae1d

**Comment by EndlesslyFlowering** [comment]
> Sorry to bother you but I cannot get hdr_analysis from any of 2024 releases to work for me in Elden Ring.

You can't bother me with actual issues 😺

**Comment by EndlesslyFlowering** [comment]
> Yes, it does compile now successfully. It did confuse me at first by showing SDR analysis but after entering override it works now 👍 Thank you very much!

Yeah I have to think of a better solution for that.
It shows that `CSP_HDR10` is allowed as override. Elden Ring does not set the colour space so I can't do anything.

Glad that it works :)
