### ISSUE TITLE
errro x3000

### ISSUE THREAD

**Issue by IgarashiInaba** [EndlesslyFlowering/ReShade_HDR_shaders#20]
![QQ截图20240302204913](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/assets/24621077/c8d2e789-cfbd-4240-8802-af43b19faf8d)
colour_space.fxh line297

  ui_text     = INFO_TEXT;  → missing ""
  
  when i corrected as → ui_text     = "INFO_TEXT";
  its seems fine now.
  
  did i missing something? my reshade is 6.0.1.

**Comment by EndlesslyFlowering** [comment]
Which game is this?

**Comment by EndlesslyFlowering** [comment]
Any update?

**Comment by IgarashiInaba** [comment]
ah sorry i forgot reply.
its little bit long time so i didnt remember which preset i had ever use.

but your project title name in reshade is name as "lilium" right? i click them all and didnt see error now.

**Comment by IgarashiInaba** [comment]
> Any update?

ah sorry i forgot reply.
its little bit long time so i didnt remember which preset i had ever use.

but your project title name in reshade is name as "lilium" right? i click them all and didnt see error now.

**Comment by EndlesslyFlowering** [comment]
> but your project title name in reshade is name as "lilium" right?
yes

nice that it works now :)
