### ISSUE TITLE
Black floor fix failed to compile

### ISSUE THREAD

**Issue by troco72** [EndlesslyFlowering/ReShade_HDR_shaders#21]
Newest reshade addon version. Newest version of your shaders as well. 

Error X3506: 'F__ConvertToWorkingCsp' Not all control paths return a value

Baldurs gate 3

Any idea what the issue is?

**Comment by EndlesslyFlowering** [comment]
Already fixed in latest master 🐱

**Comment by troco72** [comment]
> Already fixed in latest master 🐱

Sorry I'm a bit slow. I downloaded the newest version I believe, am I doing something wrong? Or are you saying your newest unreleased version has a fix? 

Again, sorry for the trouble <3

**Comment by EndlesslyFlowering** [comment]
Here:
https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/archive/refs/heads/master.zip
