### ISSUE TITLE
Inverse tone-mapping in release "2024.03.30" is broken

### ISSUE THREAD

**Issue by edinsuta** [EndlesslyFlowering/ReShade_HDR_shaders#24]
I have noticed that the inverse tone-mapping (Method A, CSP_HDR10) is broken. Everything that should be red/orange has a green/yellow sickly hue/tint. Plus, the whole image is less bright/dull/grayish.

I do not know what went wrong code-wise since I am not an expert in HDR. I am simply explaining what I am seeing. If I revert to the previous release (2024.03.26), all the colors are fine.

I am using your forked AutoHDR addon in combination with your inverse tone-mapping. It all worked fine, until this release.

Release "2024.03.30":

![Banishers-Win64-Shipping 2024-04-01 01-06-21](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/assets/12500415/c3155704-5794-4ff6-99b9-0e8f88d3c4b9)

Release "2024.03.26":

![Banishers-Win64-Shipping 2024-04-01 01-08-11](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/assets/12500415/77f3498e-c49b-4da6-a1d7-304e52e69cd5)

**Comment by EndlesslyFlowering** [comment]
fixed with afed41afc855d0afe70d61e56fdf5cac4d577cb4
