### ISSUE TITLE
Shader not compiling in scRGB HDR when colour space is not set

### ISSUE THREAD

**Issue by EndlesslyFlowering** [EndlesslyFlowering/ReShade_HDR_shaders#28]
I also have a similar problem.
Since  2024.06.02, lilium__hdr_and_sdr_analysis failed to complie with Assassin's Creed Odyssey, which has no problem with 2024.04.18.
Here is [ReShade.log](https://github.com/user-attachments/files/15573202/ReShade.log)

_Originally posted by @onenowy in https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/issues/27#issuecomment-2148839453_

**Comment by EndlesslyFlowering** [comment]
@onenowy
please check the latest master [here](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/archive/refs/heads/master.zip)

**Comment by onenowy** [comment]
No compiling error, but every hdr related shaders are not working.
[ReShade.log](https://github.com/user-attachments/files/15598770/ReShade.log)

**Comment by EndlesslyFlowering** [comment]
> No compiling error, but every hdr related shaders are not working. [ReShade.log](https://github.com/user-attachments/files/15598770/ReShade.log)
> 
> EDIT: It's also not working with [https://github.com/EndlesslyFlowering/AutoHDR-ReShade](url) on hi-fi rush with latest master (compiling error with 2024.06.02), but it's working with 2024.04.18. [hi-fi-rush-ReShade.log](https://github.com/user-attachments/files/15598799/hi-fi-rush-ReShade.log)
> 
> EDIT2: setting CSP_OVERRIDE to CSP_SCRGB allows both game to work with latest master.

Yes that was an intentional change.

Glad that it works again :)

With the newest version of the AutoHDR add-on the colour space should be set correctly though.
