### ISSUE TITLE
[Proposal] Add color space outlines to CIE diagram

### ISSUE THREAD

**Issue by f1ac** [EndlesslyFlowering/ReShade_HDR_shaders#3]
Could be useful to have BT.709, DCI and Rec.2020 outlines on the color diagram optionally.

**Comment by EndlesslyFlowering** [comment]
that is on my todo list.
gonna leave this open until I implement it :)

**Comment by EndlesslyFlowering** [comment]
![1931](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/assets/19245343/c672ab4b-6094-4545-9f74-f3dc2cebdd84)
![1976](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/assets/19245343/1084d1c7-ca91-42e2-902a-966ae1d55dd2)
took a while to get to it :)

**Comment by EndlesslyFlowering** [comment]
will be in the next automated release which is in 6h 🙂

**Comment by f1ac** [comment]
Great, thanks! Any chance for multiple outlines at once? 
![image](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/assets/13987066/8b1605d9-01ed-465e-b454-1f87b09c7ce2)

**Comment by EndlesslyFlowering** [comment]
> Great, thanks! Any chance for multiple outlines at once?

Is in the next release which is in less than 2 hours.

**Comment by f1ac** [comment]
Works fine it seems :)
![image](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/assets/13987066/cb84c1fe-a41b-4e8e-a351-4cb3724a4a60)
