### ISSUE TITLE
Can I use this project with MPV?

### ISSUE THREAD

**Issue by geextahslex** [EndlesslyFlowering/ReShade_HDR_shaders#30]
Hi, I wanted to ask if this can be used with [mpv](https://github.com/mpv-player/mpv) (Command line video player) for video playback (HDR to SDR tone-mapping)?

Thank you :)

**Comment by EndlesslyFlowering** [comment]
mpv already provides really good HDR to SDR tone mapping capabilities. I have used them in the past when I didn't have an HDR display yet.

**Comment by geextahslex** [comment]
Oh okay I understand.
Do you remember your tone mapping settings? I mess around with all settings but everything feels off ^^'

**Comment by EndlesslyFlowering** [comment]
the last I used was this iirc:
```
tone-mapping=bt.2390
tone-mapping-max-boost=10
```
I also recommned:
bt.2446a or spline for tone mapping.
And these settings for experimentation:
- hdr-contrast-recovery
- hdr-contrast-smoothness
These sertings basically all need `vo=gpu-next`.
Also see the manual ( https://mpv.io/manual/master/#options-tone-mapping-param ) for how they work.

**Comment by geextahslex** [comment]
Thank you I will try them out
