### ISSUE TITLE
[Bug] CSP_OVERRIDE no longer avalible after swiching from HDR to SDR

### ISSUE THREAD

**Issue by KoKlusz** [EndlesslyFlowering/ReShade_HDR_shaders#33]
For example, here's Jusant, UE5 game, so it supports 10 bit SDR. Booting the game in SDR, the CSP_OVERRIDE option is present and working.

![2024-07-28 122339](https://github.com/user-attachments/assets/dbe5d654-de94-4aaf-b5f9-9a38d03dd141)

However, of you switch to HDR and back to SDR, the option is gone and shader in now "stuck" in the SDR mode, despite the fact it says at the top that CSP override is allowed.

![2024-07-28 122616](https://github.com/user-attachments/assets/b26549ac-0dd2-4bca-ad6a-b5cf3a5afa32)

Only fix that I've found is to reboot the game, it happens across all 10 bit SDR games that I've seen. Pretty sure it used to work fine before, so the bug might have been introduced recently, though I can't tell when exactly.

**Comment by SplitCoreGaming** [comment]
Can confirm as was about to post exact same thing. Explained very well above and exactly same issue.

**Comment by EndlesslyFlowering** [comment]
yeah I broke this somewhere
need to look into it

**Comment by EndlesslyFlowering** [comment]
@KoKlusz
can you test this file?
[colour_space.zip](https://github.com/user-attachments/files/16449038/colour_space.zip)

**Comment by KoKlusz** [comment]
> @KoKlusz can you test this file? [colour_space.zip](https://github.com/user-attachments/files/16449038/colour_space.zip)

Tested multiple games, can confirm it's working.

**Comment by EndlesslyFlowering** [comment]
thanks for testing
I'll leave this issue open until I have pushed a new release

**Comment by SplitCoreGaming** [comment]
> thanks for testing I'll leave this issue open until I have pushed a new release

Can also confirm fixed my Elden Ring issue.

**Comment by EndlesslyFlowering** [comment]
fixed wtih 6bffdda572eaed6f16e6dc82a27ec4404409a30e
