### ISSUE TITLE
Inverse Tone Mapping feature request.

### ISSUE THREAD

**Issue by ABDX80** [EndlesslyFlowering/ReShade_HDR_shaders#39]
Is it possible to get the **'Gamut Expansion'** option back for **'BT.2446 Method A'** just like the older version of this repo?
@EndlesslyFlowering

**Comment by EndlesslyFlowering** [comment]
https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/issues/29#issuecomment-2158395254
