### ISSUE TITLE
i have an issue after installing it to diablo 4 i get this "color space not supported"

### ISSUE THREAD

**Issue by FireStormKSA** [EndlesslyFlowering/ReShade_HDR_shaders#4]
![Screenshot 2023-07-22 105556](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/assets/26449992/29d238c1-132a-4e19-925c-2f68e9c9547f)

**Comment by EndlesslyFlowering** [comment]
Make sure you are on the latest version of my shaders first. Just download them again.
Also make sure the game is set to actually output HDR. It doesn't look like it from your screenshot.
If it still doesn't work, check the info text at the top of the HDR analysis shader and if you are confused by it post a picture of it here.

**Comment by FireStormKSA** [comment]
ohhh I'm dumb really sorry for wasting your time, i just noticed I'm using my monitor not my tv. I just forgot.

**Comment by FireStormKSA** [comment]
do i use full or limited rgb? for my lg cx

**Comment by EndlesslyFlowering** [comment]
> ohhh I'm dumb really sorry for wasting your time, i just noticed I'm using my monitor not my tv. I just forgot.

np

> do i use full or limited rgb? for my lg cx

full RGB with the TV to set to PC mode :)
