### ISSUE TITLE
HDR Analysis shader not working for AutoHDR

### ISSUE THREAD

**Issue by DitherMan420** [EndlesslyFlowering/ReShade_HDR_shaders#5]
Hello. I just wanted to let you know that your shader is not working in autoHDR, even when adding the correct CSP_SCSRGB override line. Do you know what's going on? Others have also confirmed this issue (see plasma tv for gaming youtube channel). Is this going to be fixed? Thank you!

**Comment by EndlesslyFlowering** [comment]
![image](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/assets/19245343/af21e939-474b-4b18-bf0b-af9121b64dce)
ReShade only has access to the SDR game and not the HDR created from AutoHDR which happens after anything ReShade has control over.
iirc AutoHDR happens in the DWM, so there is no way for ReShade to reach it.
I have build in protections so you can't do overrides which don't make sense. And overriding SDR to be read as scRGB doesn't make sense.

**Comment by DitherMan420** [comment]
> ![image](https://user-images.githubusercontent.com/19245343/256053517-af21e939-474b-4b18-bf0b-af9121b64dce.png) ReShade only has access to the SDR game and not the HDR created from AutoHDR which happens after anything ReShade has control over. iirc AutoHDR happens in the DWM, so there is no way for ReShade to reach it. I have build in protections so you can't do overrides which don't make sense. And overriding SDR (sRGB) to be read as scRGB doesn't make sense.

So is there any way to get your shaders to work with AutoHDR that you are aware of?

**Comment by EndlesslyFlowering** [comment]
> > ![image](https://user-images.githubusercontent.com/19245343/256053517-af21e939-474b-4b18-bf0b-af9121b64dce.png) ReShade only has access to the SDR game and not the HDR created from AutoHDR which happens after anything ReShade has control over. iirc AutoHDR happens in the DWM, so there is no way for ReShade to reach it. I have build in protections so you can't do overrides which don't make sense. And overriding SDR (sRGB) to be read as scRGB doesn't make sense.
> 
> So is there any way to get your shaders to work with AutoHDR that you are aware of?

Literally not possible as I understand it.

**Comment by DitherMan420** [comment]
> 

Okay thank you. I appreciate your work and the quick replies. If I wanted to just adjust the black floor level by eyesight (rather than the graphs), can I do that using your black floor fix shader? Or will that just straight up not work at all?

**Comment by EndlesslyFlowering** [comment]
> > 
> 
> Okay thank you. I appreciate your work and the quick replies. In AUTOHDR, If I wanted to just adjust the black floor level by eyesight (rather than the graphs), can I do that using your black floor fix shader? Or will that just straight up not work at all?

I prevent all my HDR shaders from being used in SDR which includes the "***HDR*** black floor fix".
