### ISSUE TITLE
lilium__hdr_analysis.fx Failed to compile

### ISSUE THREAD

**Issue by ZebedeeZ** [EndlesslyFlowering/ReShade_HDR_shaders#6]
Hi mate. Having an issue compiling lilium__hdr_analysis.fx with Need For Speed Unbound. Log attached. I'm using the latest version of Reshade and your shaders. Thanks. 
[ReShade.log](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/files/12329336/ReShade.log)

**Comment by EndlesslyFlowering** [comment]
don't have that issue in other DX12 titles and don't own the game either.
try the following things:
- clear the effect cache
- delete all `lilium_***` files and folders and redownload the [latest release](https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/releases/download/2023.08.12/2023.08.12.7z)
- delete the `ReShadePreset.ini` file
- try uninstalling ReShade and delete all for leftover files and folders in the game's folder (usually they are all named "Reshade...") and reinstall ReShade again afterwards

**Comment by Ilan-Y** [comment]
I have the same issue with Sekiro and also Remnant 2 (the only games I have tried this tool with so far). I tried the offered in the comment above but the issue persists.
The only way I can get it to work is with the older version of the tool, from July 26.

**Comment by EndlesslyFlowering** [comment]
Hopefully fixed it.
Check the next automated release in 2 hours.

**Comment by Ilan-Y** [comment]
> Hopefully fixed it. Check the next automated release in 2 hours.

Yes, it's fixed!
TY.

**Comment by ZebedeeZ** [comment]
Yes working here as well, thanks

**Comment by EndlesslyFlowering** [comment]
> > Hopefully fixed it. Check the next automated release in 2 hours.
> 
> Yes, it's fixed! TY.



> Yes working here as well, thanks

nice :)

**Comment by jarrard** [comment]
FYI   2023 8 18 broke it again.

**Comment by EndlesslyFlowering** [comment]
> FYI 2023 8 18 broke it again.

I fixed it in that release though?

**Comment by volfin** [comment]
2023 8 18 broken for me also. "Variable PingPongChecks used without having been fully initialized."

**Comment by jarrard** [comment]
It doesn't compile in performance mode I found out. Something I didn't realize was a issue.

**Comment by EndlesslyFlowering** [comment]
> 2023 8 18 broken for me also. "Variable PingPongChecks used without having been fully initialized." Strange part is, it only fails when you check performance mode. With that off it compiles.

@volfin and @jarrard
I fixed that for the next release :)
