### ISSUE TITLE
(ERROR)

### ISSUE THREAD

**Issue by kaimian** [EndlesslyFlowering/ReShade_HDR_shaders#7]
The shader is giving me this error: Only HDR Spaces are supported!
I have a simple HDR10 display (Acer vg240ys) using a HDMI 2.0 cable and with HDR turned on. Also auto HDR on windows turned on.
I'm trying to make use of this incredible shader but it is giving me this error and not working at all.
I Installed the AutoHDR by MajorPainTheCactus and it is working normally.
Any help would be appreciated, thank you in advance.

**Comment by EndlesslyFlowering** [comment]
You can't use it on AutoHDR because that runs after anything ReShade can touch.

**Comment by kaimian** [comment]
> You can't use it on AutoHDR because that runs after anything ReShade can touch.

Sorry but what AutoHDR are you referring to? Windows AutoHDR or MajorPain's AutoHDR?

**Comment by EndlesslyFlowering** [comment]
Windows AutoHDR
