### ISSUE TITLE
Could you write a user-guide or a quick reference guide to help us learn how to use your shaders better?

### ISSUE THREAD

**Issue by DitherMan420** [EndlesslyFlowering/ReShade_HDR_shaders#8]
Just curious if you have any further documentation for the shaders.

My main question: What exactly does the "inverse tone mapping" shader do? How does this differ from the other tone mapping and gamma shaders?

**Comment by EndlesslyFlowering** [comment]
guides are planned. I am currently busy with other stuff though.

inverse tone mapping is the inverse (opposite) of tone mapping it expands a low dynamic range (or SDR) image into a high dynamic range image
while regular tone mapping is usually compressing HDR into SDR but in the case of my shaders it's HDR to HDR with lower brightness. which is meant for games where no HDR options exist or you want to replace the games' tone mapper (tone mappers of games are usually not as good as my options as what some users reported)

**Comment by EndlesslyFlowering** [comment]
now tracked in the Public TODO list

**Comment by Day0Dreamer** [comment]
> guides are planned. I am currently busy with other stuff though.
> 
> inverse tone mapping is the inverse (opposite) of tone mapping it expands a low dynamic range (or SDR) image into a high dynamic range image while regular tone mapping is usually compressing HDR into SDR but in the case of my shaders it's HDR to HDR with lower brightness. which is meant for games where no HDR options exist or you want to replace the games' tone mapper (tone mappers of games are usually not as good as my options as what some users reported)

Wish that was at least in README.md
