### ISSUE TITLE
How do I use the adaptive tonemapper?

### ISSUE THREAD

**Issue by marat569** [EndlesslyFlowering/ReShade_HDR_shaders#9]
I've tried to mess around with it, but there are too much sliders and I'm a pepega.

I assume its something similar to SK's Adaptive Tonemapping slider -- but I can set a preferred max nits and it will dynamically tonemap stuff

Either way if you can help me out here I'd really appreciate it!

Just an explanation of the core settings I need to change, what they do (and why I need to change them) -- that's enough for me to be confident enough every future game

**Comment by EndlesslyFlowering** [comment]
the adaptive mode calculates maxCLL per frame and uses that as maxCLL input for the tone mapping option of your choice
all the options that you can change for adaptive tone mapping are explained in their respective tooltips

idk what SK's Adaptive Tonemapping does

**Comment by marat569** [comment]
What settings should I change if say I have a 1500 nit image and want to tonemap it down to idk 800 nits?

**Comment by EndlesslyFlowering** [comment]
just the target brightness to 800

**Comment by marat569** [comment]
can you unblock me on discord please

**Comment by EndlesslyFlowering** [comment]
> can you unblock me on discord please

The reason why I blocked you has not changed.

**Comment by Day0Dreamer** [comment]
> the adaptive mode calculates maxCLL per frame and uses that as maxCLL input for the tone mapping option of your choice all the options that you can change for adaptive tone mapping are explained in their respective tooltips
> 
> idk what SK's Adaptive Tonemapping does

Wish that was at least in README.md
